### ISSUE TITLE
Actually uses exceptions

### ISSUE THREAD

**Issue by mje-nz** [quicknir/wise_enum#15] opened 2019-02-19 21:10 UTC
The readme says wise_enum doesn't use any heap or exceptions, which would be great for embedded applications. Unfortunately it's not true -- std::optional::value() and wise_enum::optional::value() throw bad_optional_access.

**Comment by quicknir** [comment] 2019-02-19 21:13
I should probably say there is no mandatory use of exceptions; you can do all your error handling without using exceptions. In substance however this doesn't change the fact that wise_enum is perfectly suitable for embedded; if you want to use it on embedded then simply build with -fnoexceptions (which you already do probably) and make sure you check the optional is full before accessing with it `*` or `value`.

**Comment by quicknir** [comment] 2019-02-19 21:44
Note: I don't do much embedded. If you don't build with -fnoexceptions for some reason, let me know the reason why and I could consider having a macro that when defined completely removes the exception related code from the wise_enum version of optional.

Or, you can define your own optional very easily by simply copy pasting mine, and removing the exception stuff, and using the appropriate macro to ensure that your definition of optional is used. If this is an issue for you then it will almost certainly be worth having your own version of optional anyway...

**Comment by mje-nz** [comment] 2019-02-19 21:59
With -fno-exceptions, `throw` in user code is a compile-time error, so `optional.h` doesn't compile.

Yesterday I tweaked `from_string` to use an out-param and return an error code instead of returning an optional, and it compiles down very nicely and works great on an ARMv6-M target. Embedded codebases are a bit behind the times when it comes to modern C++ unfortunately!

**Comment by quicknir** [comment] 2019-02-19 22:25
Dang, you're right, my bad! Thanks for taking the time to create an issue. Interestingly gcc actually compiles it for me as long as you don't use value, since optional is a template. Clang however doesn't (which is probably more correct). So I will put my money where my mouth is and add a macro that if enabled disables all the exception related methods (you'll have to use operator*). Does that seem alright?

I imagine they are and I can understand the reasons for the exception situation, however I still think an optional should be preferable to out-param + error code?

**Comment by mje-nz** [comment] 2019-02-19 22:55
No worries, thanks for the great library.

So using it would look like this?
```cpp
auto x1 = wise_enum::from_string<Color>("GREEN");
if (x1) {
  // Do stuff with *x1
}
```
That would definitely be better, I'd totally use an optional if I had one available.

**Comment by quicknir** [comment] 2019-02-19 22:59
Yep, that's exactly correct. I will make the changes probably this weekend. Though, keep in mind my optional implementation is still quite limited. I will make the changes in my library either way but if I were you, what I would actually do is find a good optional implementation online (there are quite a number, including those targeting e.g. C++11 if you are not on 17), copy the files into your source tree, and simply delete all the exception related stuff. Then you can use that optional all over your codebase. And you can define the macro in my library so that you get this generic optional from wise_enum.

 Optional has its limitations though since it doesn't store any error information; so I'd like at other alternatives (expected, outcome) etc; many of them explicitly try to cater to a no exception universe. I used optional simply because there's only one possible reason for the error :-)

**Comment by quicknir** [comment] 2019-05-18 17:23
Hey, took me a bit, but i pushed some stuff to master that should make it truly usable without exceptions (and i updated the README as well). Please feel free to leave any feedback on the issue, positive or negative! I will close this for now but please do re-open if there is a problem (if you want to confirm it works, just comment without re-opening).

**Closed as completed by quicknir** 2019-05-18 17:23 UTC

**Comment by ramboerik** [comment] 2019-06-04 19:19
Nice, I can confirm that the it works for arduino 😃

**Comment by quicknir** [comment] 2019-06-04 19:39
@ramboerik Nice! Thanks for taking the time to confirm :-)
